Fix importer crash caused by use of an Django internal cache variable.
Seems like this may have first occurred with the upgrade to Django
1.5, but not sure. The error was:  AttributeError: 'Options' object
has no attribute '_name_map'. (#387)